#DB properties:
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/City
    username: sa
    password:
    hikari:
      connection-init-sql: create if not exists table city(id int primary key)